### ISSUE TITLE
IllegalArgumentException when used sentinel

### ISSUE THREAD

**Issue by shaaimin** [RediSearch/lettusearch#3]
I got IllegalArgumentException when used sentinel.
Caused by: java.lang.IllegalArgumentException: hostname can't be null
	at java.net.InetSocketAddress.checkHost(InetSocketAddress.java:149) ~[?:?]
	at java.net.InetSocketAddress.createUnresolved(InetSocketAddress.java:254) ~[?:?]
	at io.lettuce.core.resource.SocketAddressResolver.resolve(SocketAddressResolver.java:91) ~[lettuce-core-5.1.8.RELEASE.jar:?]
	at io.lettuce.core.resource.SocketAddressResolver.resolve(SocketAddressResolver.java:71) ~[lettuce-core-5.1.8.RELEASE.jar:?]
	at com.redislabs.lettusearch.RediSearchClient.lambda$getSocketAddress$6(RediSearchClient.java:229) ~[lettusearch-1.5.3.jar:?]
	at reactor.core.publisher.MonoCallable.subscribe(MonoCallable.java:56) ~[reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
	at reactor.core.publisher.MonoPeek.subscribe(MonoPeek.java:71) ~[reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
	at reactor.core.publisher.MonoPeek.subscribe(MonoPeek.java:71) ~[reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
	at reactor.core.publisher.MonoPeek.subscribe(MonoPeek.java:71) ~[reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
	at reactor.core.publisher.Mono.subscribe(Mono.java:3852) ~[reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
	at reactor.core.publisher.Mono.subscribeWith(Mono.java:3958) ~[reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
	at reactor.core.publisher.Mono.subscribe(Mono.java:3846) ~[reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
	at reactor.core.publisher.Mono.subscribe(Mono.java:3813) ~[reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
	at reactor.core.publisher.Mono.subscribe(Mono.java:3785) ~[reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
	at io.lettuce.core.AbstractRedisClient.initializeChannelAsync(AbstractRedisClient.java:290) ~[lettuce-core-5.1.8.RELEASE.jar:?]
	at com.redislabs.lettusearch.RediSearchClient.connectStatefulAsync(RediSearchClient.java:177) ~[lettusearch-1.5.3.jar:?]
	at com.redislabs.lettusearch.RediSearchClient.connectStandaloneAsync(RediSearchClient.java:134) ~[lettusearch-1.5.3.jar:?]
	at com.redislabs.lettusearch.RediSearchClient.connect(RediSearchClient.java:93) ~[lettusearch-1.5.3.jar:?]
	at com.redislabs.lettusearch.RediSearchClient.connect(RediSearchClient.java:86) ~[lettusearch-1.5.3.jar:?]

**Comment by shaaimin** [comment]
the following are my configuration.

@Configuration
@ConfigurationProperties(prefix = "spring.redisearch")
public class RediSearchConfig {
	@Autowired
	private RedisProperties props;
	
	@Bean(destroyMethod = "shutdown")
	ClientResources clientResources() {
		return DefaultClientResources.create();
	}

    private RedisURI sentinelConfigurationToRedisURI(Sentinel sentinel) {
        List<String> sentinels = sentinel.getNodes();
        RedisURI.Builder builder = RedisURI.builder();
        for (String node : sentinels) {
            builder = builder.withSentinel(node.split(":")[0], Integer.parseInt(node.split(":")[1]));
        }

        builder = builder.withSentinelMasterId(sentinel.getMaster());

        return builder.build();
    }

	@Bean(destroyMethod = "shutdown")
	RediSearchClient client(ClientResources clientResources) {
        RedisURI redisURI = sentinelConfigurationToRedisURI(props.getSentinel());

        String password = props.getPassword();
		if (password != null) {
			redisURI.setPassword(password);
		}
        Duration timeout = props.getTimeout();
		if (timeout != null) {
			redisURI.setTimeout(timeout);
		}

		return RediSearchClient.create(clientResources, redisURI);
	}

**Comment by shaaimin** [comment]
i confirmed that RediSearchClient.java.
It seems that only connectStandaloneAsync had been implemented, connectSentinelAsync should be implemented for connection to a Redis Sentinel.

**Comment by jruaux** [comment]
Thanks for reporting this issue. I will add support for sentinel connections in the next version of LettuSearch.

**Comment by jruaux** [comment]
sentinel support has been added in version 1.6.0
