### ISSUE TITLE
Copied lettuce classes are problematic -nan ft.info

### ISSUE THREAD

**Issue by krm1312** [RediSearch/lettusearch#33]
Various lettuce core classes are copied into this library (with same name and package).  This seems problematic.  I was debugging why ftInfo throws a NumberFormatException and it appears that the copy of LettuceStrings in this package has been modified to deal with it, but, the version of LettuceStrings actually being used (by random classpath ordering) is that from the lettuce package which does not have this condition:

```java

        if ("-nan".equals(s)) {
            return Double.NaN;
        }
```

ft.info snippet with -nan
```
44)  1) "bytes_collected"
     2) "0"
     3) "total_ms_run"
     4) "0"
     5) "total_cycles"
     6) "0"
     7) "avarage_cycle_time_ms"
     8) "-nan"
     9) "last_run_time_ms"
    10) "0"
    11) "gc_numeric_trees_missed"
    12) "0"
    13) "gc_blocks_denied"
    14) "0"
```

Exception:
```

java.lang.NumberFormatException: For input string: "-nan"
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054) ~[na:na]
	at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[na:na]
	at java.base/java.lang.Double.parseDouble(Double.java:543) ~[na:na]
	at io.lettuce.core.internal.LettuceStrings.toDouble(LettuceStrings.java:97) ~[lettuce-core-6.0.0.RELEASE.jar:6.0.0.RELEASE]
	at io.lettuce.core.protocol.RedisStateMachine.readFloat(RedisStateMachine.java:627) ~[lettuce-core-6.0.0.RELEASE.jar:6.0.0.RELEASE]
	at io.lettuce.core.protocol.RedisStateMachine.handleFloat(RedisStateMachine.java:425) ~[lettuce-core-6.0.0.RELEASE.jar:6.0.0.RELEASE]
	at io.lettuce.core.protocol.RedisStateMachine$State$Type.handle(RedisStateMachine.java:206) ~[lettuce-core-6.0.0.RELEASE.jar:6.0.0.RELEASE]
	at io.lettuce.core.protocol.RedisStateMachine.doDecode(RedisStateMachine.java:334) ~[lettuce-core-6.0.0.RELEASE.jar:6.0.0.RELEASE]
	at io.lettuce.core.protocol.RedisStateMachine.decode(RedisStateMachine.java:295) ~[lettuce-core-6.0.0.RELEASE.jar:6.0.0.RELEASE]
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:799) ~[lettuce-core-6.0.0.RELEASE.jar:6.0.0.RELEASE]
	at io.lettuce.core.protocol.CommandHandler.decode0(CommandHandler.java:750) ~[lettuce-core-6.0.0.RELEASE.jar:6.0.0.RELEASE]
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:724) ~[lettuce-core-6.0.0.RELEASE.jar:6.0.0.RELEASE]
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:618) ~[lettuce-core-6.0.0.RELEASE.jar:6.0.0.RELEASE]
	at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:560) ~[lettuce-core-6.0.0.RELEASE.jar:6.0.0.RELEASE]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.52.Final.jar:4.1.52.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

**Comment by jruaux** [comment]
Yes I agree this is a problem. I forgot that classpath order could break this hack. Thanks for submitting a PR against Lettuce. I will look at fixing the other 2 copied classes, and more generally work on removing the remaining code duplication, especially `RediSearchClient` and `StatefulRediSearchConnectionImpl`
